import tap from 'tap';
import { normalizeExchangeGroups, rabbotConfigFromExchangeGroups } from '../src/exchangeGroups';
import _ from 'lodash';

const simpleCase = {
  keys: 'simplekey',
};

const noRetryCase = {
  retries: 0,
  keys: 'noretrykey',
};

const complexCase = {
  retryDelay: 10,
  exchange: 'conf.ex',
  queue: {
    name: 'autodeletequeue',
    autoDelete: true,
  },
  retryQueue: 'crazyretryqueuename',
  keys: ['somekey', 'someotherkey'],
};

const exchangeGroups = {
  simpleCase,
  noRetryCase,
  complexCase,
};

tap.test('test exchange group normalization', async (t) => {
  const finalGroups = normalizeExchangeGroups(exchangeGroups);

  t.ok(finalGroups.simpleCase.exchange.name === 'simpleCase', 'Exchange should be named the same as the group');
  t.ok(finalGroups.simpleCase.queue.name === 'simpleCase.q', 'Exchange should be named the same as the group with q');
  t.ok(finalGroups.simpleCase.retries > 0 &&
       finalGroups.simpleCase.retryDelay > 0 &&
       finalGroups.simpleCase.retryExchange &&
       finalGroups.simpleCase.retryQueue &&
       finalGroups.simpleCase.rejectedExchange &&
       finalGroups.simpleCase.rejectedQueue, 'Retry queues should be generated by default');

  t.ok(!finalGroups.noRetryCase.retryExchange &&
       !finalGroups.noRetryCase.retryQueue &&
       !finalGroups.noRetryCase.rejectedExchange &&
       !finalGroups.noRetryCase.rejectedQueue, 'Retry queues should not be generated when retries is set to 0');

  t.ok(finalGroups.complexCase.queue.name === complexCase.queue.name, 'Deep queue name is accepted');
  t.ok(finalGroups.complexCase.queue.autoDelete === complexCase.queue.autoDelete, 'Deep queue properties are accepted');
  t.ok(finalGroups.complexCase.retryQueue.name === complexCase.retryQueue, 'Additional queue overrides are accepted.');
});

tap.test('test exchange group to rabbot config translation', async (t) => {
  const finalGroups = normalizeExchangeGroups(exchangeGroups);
  const rabbotConfig = rabbotConfigFromExchangeGroups(finalGroups);

  t.ok(_.find(rabbotConfig.queues, ['name', finalGroups.complexCase.queue.name]).autoDelete === complexCase.queue.autoDelete, 'Specific configuration propogates to rabbot config');
});
